FROM_LANGUAGE = "en"
TO_LANGUAGE = "uk"

API_URL=f"https://translate.googleapis.com/translate_a/single?client=gtx&sl={FROM_LANGUAGE}&tl={TO_LANGUAGE}&dt=t&q="

ANKI_JSON_PATH = "./anki cards/1000_Basic_English_Words/deck.json"

WORD = 1
PRONUNCIATION = 2
PART_OF_SPEECH = 3
DEFINITION = 4
EXAMPLE = 5
CLOZE = 6
IMG = 7
SOUND_WORD = 8
SOUND_EXAMPLE = 9
TRANSLATE_WORD = 10
TRANSLATE_CLOZE = 11
TRANSLATE_DEFINITION = 12

NUMBER_OF_THREADS = 10

RED_TEXT = "\033[91m"
RESET_TEXT_COLOR = "\033[0m"
